import { pgTable, text, timestamp, varchar } from "drizzle-orm/pg-core";
import { user } from "./auth";

/**
 * Single-use, targeted friend invite links (CAMP-031).
 *
 * Each row represents one invite link generated by a user.
 * The link can optionally be targeted at a specific Steam friend (by their Steam ID).
 * It expires 14 days after creation and is consumed when accepted.
 */
export const friendInvites = pgTable("friend_invites", {
  token: varchar("token", { length: 64 }).primaryKey(),
  inviterId: text("inviter_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  // The Steam ID of the intended recipient (optional — can be shared with anyone).
  targetSteamId: varchar("target_steam_id", { length: 20 }),
  expiresAt: timestamp("expires_at").notNull(),
  usedAt: timestamp("used_at"),
  usedBy: text("used_by").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
